name: Production - Deploy static website

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deployment_token:
        description: 'Production deployment password'
        required: true
        type: string
env:
  AWS_REGION: eu-north-1
  S3_BUCKET: "2303031300019"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Verify deployment password
      env:
        INPUT_TOKEN: ${{ inputs.deployment_token }}
        EXPECTED_TOKEN: ${{ secrets.PRODUCTION_DEPLOYMENT_TOKEN }}
      run: |
        if [ "$INPUT_TOKEN" != "$EXPECTED_TOKEN" ]; then
          echo "Deployment password verification failed."
          exit 1
        fi
        echo "Deployment password verified."

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy index-prod.html as index.html
      run: cp index-prod.html index.html

    - name: Copy files
      run: |
          aws s3 cp . s3://${{ env.S3_BUCKET }}/ --recursive --exclude "*" --include "*.html" --include "images/*"
          echo "Deployment done"
